<?php

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_query_alter().
 */
function rng_conflict_query_alter(AlterableInterface $query) {
  if ($query->hasTag('rng_register')) {
    /** @var \Drupal\rng_conflict\RngConflictProviderInterface $conflict_provider */
    $conflict_provider = \Drupal::service('rng_conflict.conflict_provider');
    $conflict_provider->alterQuery($query);
  }
}
